###########		 본인docker계정이름
### 주의 ###		본인docker레포지토리 이름
###########		꼭 확인해주세요 !!! 복붙하시고 수정 꼭 하셔야합니다.

- name: Docker Image Build and Push
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t ricky110/ricky110 java-hello-world/
    - command: docker login -u ricky110 -p "{{ lookup('env', 'PASS') }}"
    - command: docker push ricky110/ricky110
    - command: docker logout

- name: Docker Run
  hosts: docker_host
  gather_facts: false
  
  tasks:
    - command: docker container rm -f java-hello-world
      ignore_errors: yes
    - command: docker container run -d -p 8080:8080 --name java-hello-world ricky110/ricky110
